### ISSUE TITLE
Consider distribute this repository under an open source license

### ISSUE THREAD

**Issue by ShamrockLee** [study-ml/word2vec-demo#1]
Just came here from the Facebook post. Thank you for this great project!

It is still one step away to become open-source. Without a license, the whole repository is all-right-reserved. That is, no one could download and use it legally except you.

It's quite easy to add a license -- just follow the GitHub documentation and add a LICENSE file to this repository.

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

Here's a website created by by GitHub that helps people choose a license:
https://choosealicense.com/

Some licenses I have heard of (from the most permissive to the most copy-left):

*   [BSD0](https://en.wikipedia.org/wiki/BSD_licenses#0-clause_license_(%22BSD_Zero_Clause_License%22)): Permit everyone to use, modify, and redistribute it freely without any limitation.

*   [MIT License](https://en.wikipedia.org/wiki/MIT_License?wprov=sfla1): Permit everyone to use, modify, and redistrimute it freely as long as they give credit to you by mentioning your name (attribution).

*   [GNU LGPL](https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License?wprov=sfla1): Permit everyone to use, modify, and redistribute it, but requiring the redistributed program to open source and license under GNU LGPL or GNU GPL.

*   [GNU GPL](https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License?wprov=sfla1): Similar to GNU LGPL, but requires programs that uses this project as a library to also open source and license under GNU GPL.

*   [GNU AGPL](https://en.wikipedia.org/wiki/GNU_Affero_General_Public_License?wprov=sfla1): Since this project can be run on a server and become a SaaS, GNU AGPL extends GNU GPL by requiring anyone who run this project or its derivation on their server publicly to open source their work.

**Comment by HemingwayLee** [comment]
MIT license has been added, thanks a lot for letting me know.
